### PR TITLE
Updated App.css with dark theme

### PR DESCRIPTION
**Pull request by Imagineer99**
Dark theme added as default.

### CODE REVIEW

**Comment by Imagineer99** [comment]
image

**Comment by codethazine** [comment]
Could you add a Dark/Light Mode toggle on the top-right? Also maybe set the BG to dark blue? Black is a tad bit too much

**Comment by Imagineer99** [comment]
Yes I agree, I will update the theme to be more subtle and add a lightswitch.

**Comment by Imagineer99** [comment]
image
Do you think this is more rizz?

**Comment by codethazine** [comment]
Awesome! Thanks for the contrib. Added a mode toggle upper right side

**Pull request merged**
